//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace WebApplication.Models
{
    public partial class SchoolModel : DbContext
{
    public SchoolModel()
        : base("name=SchoolModel")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Course> Course { get; set; }
    public virtual DbSet<Department> Department { get; set; }
    public virtual DbSet<Person> Person { get; set; }
    public virtual DbSet<StudentGrade> StudentGrade { get; set; }
    }
}
